apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: gcr.io/couchbase-hackathon/couchbase-spring-data-sample
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.01"
            memory: 256Mi            
          limits:
            cpu: "1"
            memory: 1024Mi     
---
apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  selector:
    app: sample
  ports:
      - port: 8080
  type: ClusterIP